apiVersion: v1
kind: Secret
metadata:
  name: openschool-secrets
type: Opaque
stringData:
  SUPABASE_URL: "https://supabasekong-f4kgk0wwokk8800w8kkswk4w.coolify.miraiyug.com"
  SUPABASE_SERVICE_ROLE_KEY: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTc3MTA2Nzk0MCwiZXhwIjo0OTI2NzQxNTQwLCJyb2xlIjoic2VydmljZV9yb2xlIn0.PObb997H20p5B_21LnhJsz7XXknlZkbOMcAhyu8jKwQ"
  NEXT_PUBLIC_SUPABASE_URL: "https://supabasekong-f4kgk0wwokk8800w8kkswk4w.coolify.miraiyug.com"
  NEXT_PUBLIC_SUPABASE_ANON_KEY: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTc3MTA2Nzk0MCwiZXhwIjo0OTI2NzQxNTQwLCJyb2xlIjoiYW5vbiJ9.DrQgrGFo_fU6VGHvQc3be0IeoS4b3-5EiuxGyX6cXYc"
  SERVICE_SUPABASESERVICE_KEY: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTc3MTA2Nzk0MCwiZXhwIjo0OTI2NzQxNTQwLCJyb2xlIjoic2VydmljZV9yb2xlIn0.PObb997H20p5B_21LnhJsz7XXknlZkbOMcAhyu8jKwQ"
  NEXT_PUBLIC_KEYCLOAK_ISSUER: "https://keycloak.miraiyug.com/realms/Mirai-LMS"
  KEYCLOAK_ISSUER: "https://keycloak.miraiyug.com/realms/Mirai-LMS"
  NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: "openschool-web"
  KEYCLOAK_CLIENT_ID: "openschool-web"
  KEYCLOAK_CLIENT_SECRET: "ImLQ7vk76tFbUnAvWMzvxpJOQRbYB8mw"
  NEXTAUTH_SECRET: "7a8b9c0d1e2f3g4h5i6j7k8l9m0n1o2p"
  NEXTAUTH_URL: "http://localhost:3000"
  ANT_MEDIA_HASH_SECRET: "your_ams_hash_secret_here"
  ADMIN_EMAIL: "shimpidipak81@gmail.com"