apiVersion: v1
kind: Service
metadata:
  name: openschool-web-service
spec:
  selector:
    app: openschool-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
